# Generated by Django 5.2.1 on 2025-05-12 14:30

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=doctors.models.doctor_profile_path, verbose_name='Photo de profil'),
        ),
    ]
