# Generated by Django 5.2.1 on 2025-05-10 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExamenClinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.CharField(blank=True, max_length=10, null=True)),
                ('taille', models.CharField(blank=True, max_length=10, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('fr_cardiaque', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fréquence cardiaque')),
                ('fr_respiratoire', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fréquence respiratoire')),
                ('sa_o2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Saturation en oxygène')),
                ('conj_muq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conjonctives et muqueuses')),
                ('atcd_med', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('atcd_chir', models.TextField(blank=True, null=True, verbose_name='Antécédents chirurgicaux')),
                ('atcd_fam', models.TextField(blank=True, null=True, verbose_name='Antécédents familiaux')),
                ('mode_vie', models.TextField(blank=True, null=True, verbose_name='Mode de vie')),
                ('plaintes', models.TextField(blank=True, null=True)),
                ('examen_physique', models.TextField(blank=True, null=True)),
                ('examen_physique_1', models.TextField(blank=True, null=True)),
                ('examen_physique_2', models.TextField(blank=True, null=True)),
                ('examen_physique_3', models.TextField(blank=True, null=True)),
                ('hypothese_diagnostics', models.TextField(blank=True, null=True, verbose_name='Hypothèses diagnostiques')),
                ('diagnostics', models.TextField(blank=True, null=True)),
                ('note_medecin', models.TextField(blank=True, null=True, verbose_name='Note du médecin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_clinique', to='examinations.consultation')),
            ],
            options={
                'verbose_name': 'Examen clinique',
                'verbose_name_plural': 'Examens cliniques',
            },
        ),
        migrations.CreateModel(
            name='ExamenParaclinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_paracliniques', to='examinations.consultation')),
            ],
            options={
                'verbose_name': 'Examen paraclinique',
                'verbose_name_plural': 'Examens paracliniques',
                'ordering': ['-date_demande'],
            },
        ),
    ]
